// 一鍵範例：每筆都是可直接化簡的完整程式（含 library 引用）
export const EXAMPLES = [
  { group: '入門', title: '(λx.x) y → y（恆等）', maxSteps: 50,
    code: '(λx. x) y', desc: '最基本的 β-reduction：把 y 代入 x。' },
  { group: '入門', title: 'K a b → a', maxSteps: 50,
    code: 'K a b', desc: 'K = λx.λy.x，只取第一個引數。' },
  { group: '入門', title: 'S K K x → x（S-K 恆等）', maxSteps: 100,
    code: 'S K K x', desc: 'SKK 等價於 I，展示多步化簡。' },
  { group: '入門', title: '(λx.λy.x) y（α-轉換示範）', maxSteps: 50,
    code: '(λx. λy. x) y', desc: '若直接代入 y 會被 λy 捕獲，直譯器會先做 α-轉換。觀察步驟說明。' },
  { group: '布林', title: 'AND TRUE FALSE → FALSE', maxSteps: 100,
    code: 'AND TRUE FALSE', desc: 'TRUE = λt.λf.t，先選出第一個分支。' },
  { group: '布林', title: 'OR FALSE FALSE → FALSE', maxSteps: 100,
    code: 'OR FALSE FALSE', desc: 'OR = λp.λq. p p q。' },
  { group: '布林', title: 'NOT TRUE → FALSE', maxSteps: 100,
    code: 'NOT TRUE', desc: 'NOT = λp. p FALSE TRUE。' },
  { group: '布林', title: 'IF TRUE a b → a', maxSteps: 100,
    code: 'IF TRUE a b', desc: 'IF 即把布林當選擇器。' },
  { group: '算術', title: 'SUCC 2 → 3', maxSteps: 100,
    code: 'SUCC 2', desc: '後繼函數：λn.λf.λx. f (n f x)。數字 2 會自動展開為 Church 2。' },
  { group: '算術', title: 'PLUS 2 3 → 5', maxSteps: 200,
    code: 'PLUS 2 3', desc: '加法經典展示，終點會解讀為 5。' },
  { group: '算術', title: 'MULT 2 3 → 6', maxSteps: 200,
    code: 'MULT 2 3', desc: '乘法：λm.λn.λf. m (n f)。' },
  { group: '算術', title: 'EXP 2 3 → 8', maxSteps: 300,
    code: 'EXP 2 3', desc: '冪次：λm.λn. n m。' },
  { group: '算術', title: 'PRED 3 → 2', maxSteps: 300,
    code: 'PRED 3', desc: 'Church 最巧妙的定義之一：用 Pair 從 (0,0) 迭代 n 次取第一元。' },
  { group: '算術', title: 'SUB 5 2 → 3', maxSteps: 500,
    code: 'SUB 5 2', desc: '減法 = n 次 PRED。' },
  { group: '算術', title: 'ISZERO 0 → TRUE', maxSteps: 100,
    code: 'ISZERO 0', desc: '零判斷。' },
  { group: 'Pair/List', title: 'FST (PAIR a b) → a', maxSteps: 100,
    code: 'FST (PAIR a b)', desc: 'Pair：λx.λy.λs. s x y，FST 傳入 TRUE 選出第一元。' },
  { group: 'Pair/List', title: 'HEAD (CONS a NIL) → a', maxSteps: 200,
    code: 'HEAD (CONS a NIL)', desc: 'List 以 fold 編碼，HEAD 取首元素。' },
  { group: '組合子', title: 'I (K a b) → a', maxSteps: 100,
    code: 'I (K a b)', desc: '組合子組合。' },
  { group: '組合子', title: 'Ω（發散展示）', maxSteps: 30,
    code: 'OMEGA', desc: 'Ω = (λx.x x)(λx.x x)，化簡後回到自身，頁面會偵測循環並停止。' },
  { group: '遞迴', title: 'FACT 3 → 6（Y 組合子）', maxSteps: 2000,
    code: 'FACT 3', desc: 'Y f 展開遞迴：FACT = Y (λf.λn. IF (ISZERO n) 1 (MULT n (f (PRED n))))。步驟很多，建議用自動播放。' },
  { group: '遞迴', title: 'FIB 4 → 3', maxSteps: 2000,
    code: 'FIB 4', desc: '費氏數列，展示 Church 數字的圖靈完備性。步驟很長，請耐心播放。' },
];
